$(OBJDIR)/string_util.o: $(SRCDIR)/string_util.c
	$(CC) $(CFLAGS) -c $< -o $@
$(OBJDIR)/e2fs_util.o: $(SRCDIR)/e2fs_util.c
	$(CC) $(CFLAGS) -c $< -o $@
$(OBJDIR)/e2fs.o: $(SRCDIR)/e2fs.c
	$(CC) $(CFLAGS) -c $< -o $@
$(OBJDIR)/eastlake.o: $(SRCDIR)/eastlake.c
	$(CC) $(CFLAGS) -c $< -o $@